---
- name: Update and upgrade Raspberry Pi systems
  hosts: all
  become: true
  tasks:
    - name: Check for root privileges
      command: id -u
      register: uid

    - name: Fail if not running as root
      fail:
        msg: "This playbook must be run as root."
      when: uid.stdout != "0"

    - name: Update apt cache
      apt:
        update_cache: yes
      register: update_cache

    - name: Check for upgradable packages
      command: apt list --upgradable
      register: upgradable_packages
      changed_when: false

    - name: Display upgradable packages
      debug:
        msg: "{{ upgradable_packages.stdout_lines }}"

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

