---
- name: Update and upgrade Raspberry Pi systems
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Ensure we have root privileges
      command: whoami
      register: whoami_output

    - name: Display the whoami result
      debug:
        var: whoami_output.stdout

    - name: Update apt cache
      apt:
        update_cache: yes
      register: update_cache

    - name: Check for upgradable packages
      command: apt list --upgradable
      become: true
      register: upgradable_packages
      changed_when: false

    - name: Display upgradable packages
      debug:
        msg: "{{ upgradable_packages.stdout_lines }}"

    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: dist
